apiVersion: v1
kind: ConfigMap
metadata:
  name: s3desk-caddy
  namespace: s3desk
data:
  Caddyfile: |
    {
      auto_https off
    }

    :8443 {
      tls /etc/caddy/tls/tls.crt /etc/caddy/tls/tls.key
      header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "same-origin"
      }
      reverse_proxy 127.0.0.1:8080 {
        header_up Host {host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-Proto {scheme}
      }
    }
