ingress:
  enabled: false

istio:
  virtualService:
    enabled: true
    gateways:
      - istio-system/s3desk-gw
    hosts:
      - s3desk.k8s.homelabird.com

server:
  allowedHosts:
    - s3desk.k8s.homelabird.com

rclone:
  downloadMultiThreadStreams: 8
  downloadMultiThreadCutoffMiB: 64
  downloadBufferSizeMiB: 32
  retryJitterRatio: 0.2
