import type { Dispatch, SetStateAction } from 'react'

import { useObjectsIndexing } from './useObjectsIndexing'
import { useObjectsLocationState } from './useObjectsLocationState'
import { useObjectsPageEnvironment } from './useObjectsPageEnvironment'
import { useObjectsPageQueries } from './useObjectsPageQueries'
import { useObjectsPageSearchData } from './useObjectsPageSearchData'
import { useObjectsPageViewState } from './useObjectsPageViewState'
import { useObjectsPrefetch } from './useObjectsPrefetch'
import { useObjectsTree } from './useObjectsTree'
import { useObjectsZipJobs } from './useObjectsZipJobs'

type ObjectsPageSelectionState = {
	clearSelection: () => void
	ensureObjectSelectedForContextMenu: (key: string) => void
	handleToggleSelectAll: (checked: boolean) => void
	lastSelectedObjectKey: string | null
	selectAllLoaded: () => void
	selectObjectFromCheckboxEvent: ReturnType<typeof import('./useObjectsSelectionHandlers').useObjectsSelectionHandlers>['selectObjectFromCheckboxEvent']
	selectObjectFromPointerEvent: ReturnType<typeof import('./useObjectsSelectionHandlers').useObjectsSelectionHandlers>['selectObjectFromPointerEvent']
	selectRange: (startKey: string, endKey: string) => void
	selectedCount: number
	selectedKeys: Set<string>
	setLastSelectedObjectKey: Dispatch<SetStateAction<string | null>>
	setSelectedKeys: Dispatch<SetStateAction<Set<string>>>
}

type ObjectsPageDataStateArgs = {
	environment: ReturnType<typeof useObjectsPageEnvironment>
	location: ReturnType<typeof useObjectsLocationState>
	tree: ReturnType<typeof useObjectsTree>
	view: ReturnType<typeof useObjectsPageViewState>
	queries: ReturnType<typeof useObjectsPageQueries>
	search: ReturnType<typeof useObjectsPageSearchData>
	jobs: ReturnType<typeof useObjectsZipJobs> & ReturnType<typeof useObjectsIndexing>
	selection: ObjectsPageSelectionState
	prefetch: ReturnType<typeof useObjectsPrefetch>
	handleTreeSelect: (key: string, closeDrawer: boolean) => void
}

export function buildObjectsPageDataState(args: ObjectsPageDataStateArgs) {
	return {
		activeTabId: args.location.activeTabId,
		addTab: args.location.addTab,
		allLoadedSelected: args.search.allLoadedSelected,
		api: args.environment.api,
		autoScanReady: args.view.autoScanReady,
		bucket: args.location.bucket,
		bucketOptions: args.queries.bucketOptions,
		bucketsQuery: args.queries.bucketsQuery,
		canGoBack: args.location.canGoBack,
		canGoForward: args.location.canGoForward,
		canGoUp: args.location.canGoUp,
		canDragDrop: args.view.canDragDrop,
		clearSearch: args.view.clearSearch,
		clearSelection: args.selection.clearSelection,
		closeGlobalSearch: args.view.closeGlobalSearch,
		closeTab: args.location.closeTab,
		commandPaletteOpener: args.environment.commandPaletteOpener,
		commitPathDraft: args.location.commitPathDraft,
		createJobWithRetry: args.environment.createJobWithRetry,
		debugContextMenu: args.environment.debugContextMenu,
		debugObjectsList: args.environment.debugObjectsList,
		deferredGlobalSearch: args.view.deferredGlobalSearch,
		deferredSearch: args.view.deferredSearch,
		detailsDrawerOpen: args.view.detailsDrawerOpen,
		detailsOpen: args.view.detailsOpen,
		detailsResizeHandleWidth: args.view.detailsResizeHandleWidth,
		detailsVisible: args.view.detailsVisible,
		detailsWidthUsed: args.view.detailsWidthUsed,
		dockDetails: args.view.dockDetails,
		dockTree: args.view.dockTree,
		downloadLinkProxyEnabled: args.view.downloadLinkProxyEnabled,
		emptyKind: args.search.emptyKind,
		ensureObjectSelectedForContextMenu: args.selection.ensureObjectSelectedForContextMenu,
		extFilter: args.view.extFilter,
		extOptions: args.search.extOptions,
		favoriteItems: args.queries.favoriteItems,
		favoriteKeys: args.queries.favoriteKeys,
		favoritePendingKeys: args.queries.favoritePendingKeys,
		favoriteCount: args.queries.favoriteCount,
		favoritesFirst: args.view.favoritesFirst,
		favoritesOnly: args.view.favoritesOnly,
		favoritesOpenDetails: args.view.favoritesOpenDetails,
		favoritesPaneExpanded: args.view.favoritesPaneExpanded,
		favoritesQuery: args.queries.favoritesQuery,
		favoritesSearch: args.view.favoritesSearch,
		filtersDrawerOpen: args.view.filtersDrawerOpen,
		globalSearch: args.view.globalSearch,
		globalSearchDraft: args.view.globalSearchDraft,
		globalSearchExt: args.view.globalSearchExt,
		globalSearchLimit: args.view.globalSearchLimit,
		globalSearchLimitClamped: args.search.globalSearchLimitClamped,
		globalSearchMaxModifiedMs: args.view.globalSearchMaxModifiedMs,
		globalSearchMaxSize: args.view.globalSearchMaxSize,
		globalSearchMinModifiedMs: args.view.globalSearchMinModifiedMs,
		globalSearchMinSize: args.view.globalSearchMinSize,
		globalSearchOpen: args.view.globalSearchOpen,
		globalSearchPrefix: args.view.globalSearchPrefix,
		globalSearchPrefixNormalized: args.search.globalSearchPrefixNormalized,
		globalSearchQueryText: args.search.globalSearchQueryText,
		goBack: args.location.goBack,
		goForward: args.location.goForward,
		handleBucketDropdownVisibleChange: args.prefetch.handleBucketDropdownVisibleChange,
		handleToggleSelectAll: args.selection.handleToggleSelectAll,
		handleToggleUiMode: args.view.handleToggleUiMode,
		handleTreeSelect: args.handleTreeSelect,
		highlightText: args.search.highlightText,
		indexFullReindex: args.view.indexFullReindex,
		indexObjectsJobMutation: args.jobs.indexObjectsJobMutation,
		indexPrefix: args.view.indexPrefix,
		indexedSearchErrorMessage: args.search.indexedSearchErrorMessage,
		indexedSearchItems: args.search.indexedSearchItems,
		indexedSearchNotIndexed: args.search.indexedSearchNotIndexed,
		indexedSearchQuery: args.search.indexedSearchQuery,
		isAdvanced: args.view.isAdvanced,
		isBookmarked: args.location.isBookmarked,
		isCompactList: args.view.isCompactList,
		isDesktop: args.view.isDesktop,
		isOffline: args.environment.isOffline,
		lastSelectedObjectKey: args.selection.lastSelectedObjectKey,
		layoutRef: args.view.layoutRef,
		maxModifiedMs: args.view.maxModifiedMs,
		maxSize: args.view.maxSize,
		minModifiedMs: args.view.minModifiedMs,
		minSize: args.view.minSize,
		navigateToLocation: args.location.navigateToLocation,
		objectCrudSupported: args.queries.objectCrudSupported,
		objectsQuery: args.queries.objectsQuery,
		onDetailsResizePointerDown: args.view.onDetailsResizePointerDown,
		onDetailsResizePointerMove: args.view.onDetailsResizePointerMove,
		onDetailsResizePointerUp: args.view.onDetailsResizePointerUp,
		onOpenPrefix: args.location.onOpenPrefix,
		onTreeLoadData: args.tree.onTreeLoadData,
		onTreeResizePointerDown: args.view.onTreeResizePointerDown,
		onTreeResizePointerMove: args.view.onTreeResizePointerMove,
		onTreeResizePointerUp: args.view.onTreeResizePointerUp,
		onUp: args.location.onUp,
		openGlobalSearch: args.view.openGlobalSearch,
		openPathModal: args.location.openPathModal,
		orderedVisibleObjectKeys: args.search.orderedVisibleObjectKeys,
		pathDraft: args.location.pathDraft,
		pathInputRef: args.location.pathInputRef,
		pathModalOpen: args.location.pathModalOpen,
		pathOptions: args.location.pathOptions,
		prefix: args.location.prefix,
		prefixByBucketRef: args.location.prefixByBucketRef,
		profileCapabilities: args.queries.profileCapabilities,
		selectedProfileProvider: args.queries.selectedProfile?.provider ?? null,
		queryClient: args.environment.queryClient,
		rawTotalCount: args.search.rawTotalCount,
		recentBuckets: args.location.recentBuckets,
		refreshTreeNode: args.tree.refreshTreeNode,
		resetGlobalSearch: args.view.resetGlobalSearch,
		rowIndexByObjectKey: args.search.rowIndexByObjectKey,
		rows: args.search.rows,
		screens: args.environment.screens,
		search: args.view.search,
		searchDraft: args.view.searchDraft,
		selectAllLoaded: args.selection.selectAllLoaded,
		selectObjectFromCheckboxEvent: args.selection.selectObjectFromCheckboxEvent,
		selectObjectFromPointerEvent: args.selection.selectObjectFromPointerEvent,
		selectRange: args.selection.selectRange,
		selectedCount: args.selection.selectedCount,
		selectedKeys: args.selection.selectedKeys,
		setActiveTabId: args.location.setActiveTabId,
		setAutoScanReadyKey: args.view.setAutoScanReadyKey,
		setDetailsDrawerOpen: args.view.setDetailsDrawerOpen,
		setDetailsOpen: args.view.setDetailsOpen,
		setExtFilter: args.view.setExtFilter,
		setFavoritesFirst: args.view.setFavoritesFirst,
		setFavoritesOnly: args.view.setFavoritesOnly,
		setFavoritesOpenDetails: args.view.setFavoritesOpenDetails,
		setFavoritesPaneExpanded: args.view.setFavoritesPaneExpanded,
		setFavoritesSearch: args.view.setFavoritesSearch,
		setFiltersDrawerOpen: args.view.setFiltersDrawerOpen,
		setGlobalSearch: args.view.setGlobalSearch,
		setGlobalSearchDraft: args.view.setGlobalSearchDraft,
		setGlobalSearchExt: args.view.setGlobalSearchExt,
		setGlobalSearchLimit: args.view.setGlobalSearchLimit,
		setGlobalSearchMaxModifiedMs: args.view.setGlobalSearchMaxModifiedMs,
		setGlobalSearchMaxSize: args.view.setGlobalSearchMaxSize,
		setGlobalSearchMinModifiedMs: args.view.setGlobalSearchMinModifiedMs,
		setGlobalSearchMinSize: args.view.setGlobalSearchMinSize,
		setGlobalSearchPrefix: args.view.setGlobalSearchPrefix,
		setIndexFullReindex: args.view.setIndexFullReindex,
		setIndexPrefix: args.view.setIndexPrefix,
		setLastSelectedObjectKey: args.selection.setLastSelectedObjectKey,
		setMaxModifiedMs: args.view.setMaxModifiedMs,
		setMaxSize: args.view.setMaxSize,
		setMinModifiedMs: args.view.setMinModifiedMs,
		setMinSize: args.view.setMinSize,
		setPathDraft: args.location.setPathDraft,
		setPathModalOpen: args.location.setPathModalOpen,
		setSearchDraft: args.view.setSearchDraft,
		setSelectedKeys: args.selection.setSelectedKeys,
		setSort: args.view.setSort,
		setTreeDrawerOpen: args.tree.setTreeDrawerOpen,
		setTreeExpandedKeys: args.tree.setTreeExpandedKeys,
		setTreeSelectedKeys: args.tree.setTreeSelectedKeys,
		setTypeFilter: args.view.setTypeFilter,
		setUiMode: args.view.setUiMode,
		setViewMode: args.view.setViewMode,
		showThumbnails: args.view.showThumbnails,
		someLoadedSelected: args.search.someLoadedSelected,
		sort: args.view.sort,
		tabs: args.location.tabs,
		thumbnailCache: args.view.thumbnailCache,
		toggleBookmark: args.location.toggleBookmark,
		toggleFavorite: args.queries.toggleFavorite,
		transfers: args.environment.transfers,
		treeData: args.tree.treeData,
		treeDrawerOpen: args.tree.treeDrawerOpen,
		treeExpandedKeys: args.tree.treeExpandedKeys,
		treeLoadingKeys: args.tree.treeLoadingKeys,
		treeResizeHandleWidth: args.view.treeResizeHandleWidth,
		treeSelectedKeys: args.tree.treeSelectedKeys,
		treeWidthUsed: args.view.treeWidthUsed,
		typeFilter: args.view.typeFilter,
		uploadDisabledReason: args.queries.uploadDisabledReason,
		uploadSupported: args.queries.uploadSupported,
		visibleFileCount: args.search.visibleFileCount,
		visibleObjectKeys: args.search.visibleObjectKeys,
		visiblePrefixCount: args.search.visiblePrefixCount,
		viewMode: args.view.viewMode,
		zipObjectsJobMutation: args.jobs.zipObjectsJobMutation,
		zipPrefixJobMutation: args.jobs.zipPrefixJobMutation,
	}
}
