import { CloudUploadOutlined, DeleteOutlined, DownloadOutlined, FolderAddOutlined, FolderOutlined, InfoCircleOutlined, LeftOutlined, ReloadOutlined, RightOutlined, SearchOutlined, SnippetsOutlined, UpOutlined } from '@ant-design/icons'

import type { UIAction } from './objectsActions'
import type { ObjectsActionDeps } from './objectsActionCatalogTypes'

export function buildGlobalActions(deps: ObjectsActionDeps): UIAction[] {
	return [
		{
			id: 'nav_back',
			label: 'Back',
			icon: <LeftOutlined />,
			keywords: 'history',
			enabled: !!deps.profileId && !deps.isOffline && deps.canGoBack,
			audience: 'advanced',
			run: () => deps.onGoBack(),
		},
		{
			id: 'nav_forward',
			label: 'Forward',
			icon: <RightOutlined />,
			keywords: 'history',
			enabled: !!deps.profileId && !deps.isOffline && deps.canGoForward,
			audience: 'advanced',
			run: () => deps.onGoForward(),
		},
		{
			id: 'nav_up',
			label: 'Go up',
			icon: <UpOutlined />,
			keywords: 'parent folder backspace',
			enabled: !!deps.profileId && !!deps.bucket && !deps.isOffline && deps.canGoUp,
			audience: 'advanced',
			run: () => deps.onGoUp(),
		},
		{
			id: 'toggle_details',
			label: deps.detailsVisible ? 'Hide details' : 'Show details',
			icon: <InfoCircleOutlined />,
			keywords: 'details preview panel',
			enabled: !!deps.profileId && !deps.isOffline,
			audience: 'advanced',
			run: () => deps.onToggleDetails(),
		},
		{
			id: 'open_folders',
			label: 'Folders',
			icon: <FolderOutlined />,
			keywords: 'tree navigation',
			enabled: !!deps.profileId,
			audience: 'advanced',
			run: () => deps.onOpenTreeDrawer(),
		},
		{
			id: 'refresh',
			label: 'Refresh',
			icon: <ReloadOutlined />,
			keywords: 'reload refetch',
			enabled: !!deps.profileId && !!deps.bucket && !deps.isOffline && deps.objectCrudSupported,
			run: () => deps.onRefresh(),
		},
		{
			id: 'go_to_path',
			label: 'Go to path… (Ctrl+L)',
			icon: <SearchOutlined />,
			keywords: 'ctrl+l address prefix jump',
			enabled: !!deps.profileId && !!deps.bucket && !deps.isOffline && deps.objectCrudSupported,
			audience: 'advanced',
			run: () => deps.onOpenPathModal(),
		},
		{
			id: 'upload',
			label: 'Upload…',
			icon: <CloudUploadOutlined />,
			keywords: 'upload files folder device',
			enabled: !!deps.profileId && !!deps.bucket && !deps.isOffline && deps.uploadSupported,
			run: () => deps.onOpenUpload(),
		},
		{
			id: 'new_folder',
			label: 'New folder…',
			shortcut: 'Ctrl+Shift+N',
			icon: <FolderAddOutlined />,
			keywords: 'mkdir folder',
			enabled: !!deps.profileId && !!deps.bucket && !deps.isOffline && deps.objectCrudSupported,
			run: () => deps.onOpenNewFolder(),
		},
		{
			id: 'commands',
			label: 'Commands (Ctrl+K)',
			icon: <SnippetsOutlined />,
			keywords: 'palette shortcuts',
			enabled: !!deps.profileId,
			audience: 'advanced',
			run: () => deps.onOpenCommandPalette(),
		},
		{
			id: 'transfers',
			label: 'Transfers',
			icon: <DownloadOutlined />,
			keywords: 'downloads jobs transfers',
			enabled: !!deps.profileId,
			audience: 'advanced',
			run: () => deps.onOpenTransfers(),
		},
		{
			id: 'new_tab',
			label: 'New tab',
			icon: <FolderOutlined />,
			keywords: 'tabs',
			enabled: true,
			audience: 'advanced',
			run: () => deps.onAddTab(),
		},
		{
			id: 'close_tab',
			label: 'Close tab',
			icon: <DeleteOutlined />,
			keywords: 'tabs',
			enabled: deps.tabsCount > 1 && !!deps.activeTabId,
			audience: 'advanced',
			run: () => deps.onCloseTab(deps.activeTabId),
		},
		{
			id: 'global_search',
			label: 'Global search',
			icon: <SearchOutlined />,
			keywords: 'index search',
			enabled: !!deps.profileId && !!deps.bucket && !deps.isOffline && deps.objectCrudSupported,
			audience: 'advanced',
			run: () => deps.onOpenGlobalSearch(),
		},
		{
			id: 'ui_mode',
			label: deps.isAdvanced ? 'Simple mode' : 'Advanced mode',
			icon: <SnippetsOutlined />,
			keywords: 'simple advanced view mode',
			enabled: !!deps.profileId,
			run: () => deps.onToggleUiMode(),
		},
	]
}
