import { buildObjectsPageOverlaysProps } from './buildObjectsPageOverlaysProps'
import type {
	ObjectsListVm,
	ObjectsLocationVm,
	ObjectsOperationVm,
	ObjectsPaneVm,
	ObjectsScreenArgs,
	ObjectsSelectionVm,
} from './objectsScreenTypes'
import type { ObjectsScreenListState } from './useObjectsScreenList'

type Args = Pick<ObjectsScreenArgs, 'props' | 'actions'> & {
	locationVm: ObjectsLocationVm
	listVm: ObjectsListVm
	selectionVm: ObjectsSelectionVm
	operationVm: ObjectsOperationVm
	paneVm: ObjectsPaneVm
	listState: ObjectsScreenListState
}

export function useObjectsScreenOverlays({
	props,
	locationVm,
	listVm,
	selectionVm,
	operationVm,
	paneVm,
	actions,
	listState,
}: Args) {
	return buildObjectsPageOverlaysProps({
		actions,
		apiToken: props.apiToken,
		profileId: props.profileId,
		bucket: locationVm.bucket,
		prefix: locationVm.prefix,
		isMd: !!paneVm.screens.md,
		isLg: !!paneVm.screens.lg,
		bucketOptions: listVm.bucketOptions,
		bucketsLoading: listVm.bucketsQuery.isFetching,
		selectedCount: selectionVm.selectedCount,
		filtersDrawerOpen: paneVm.filtersDrawerOpen,
		setFiltersDrawerOpen: paneVm.setFiltersDrawerOpen,
		isAdvanced: listVm.isAdvanced,
		typeFilter: listVm.typeFilter,
		setTypeFilter: listVm.setTypeFilter,
		favoritesOnly: listVm.favoritesOnly,
		setFavoritesOnly: listVm.setFavoritesOnly,
		favoritesFirst: listVm.favoritesFirst,
		setFavoritesFirst: listVm.setFavoritesFirst,
		extFilter: listVm.extFilter,
		extOptions: listVm.extOptions,
		setExtFilter: listVm.setExtFilter,
		minSize: listVm.minSize,
		maxSize: listVm.maxSize,
		setMinSize: listVm.setMinSize,
		setMaxSize: listVm.setMaxSize,
		minModifiedMs: listVm.minModifiedMs,
		maxModifiedMs: listVm.maxModifiedMs,
		setMinModifiedMs: listVm.setMinModifiedMs,
		setMaxModifiedMs: listVm.setMaxModifiedMs,
		sort: listVm.sort,
		setSort: listVm.setSort,
		resetFilters: listState.resetFilters,
		hasActiveView: listState.hasActiveView,
		pathModalOpen: locationVm.pathModalOpen,
		pathDraft: locationVm.pathDraft,
		pathOptions: locationVm.pathOptions,
		pathInputRef: locationVm.pathInputRef,
		setPathDraft: locationVm.setPathDraft,
		commitPathDraft: locationVm.commitPathDraft,
		setPathModalOpen: locationVm.setPathModalOpen,
		commandPaletteOpen: listState.commandPaletteOpen,
		commandPaletteQuery: listState.commandPaletteQuery,
		commandPaletteItems: listState.commandPaletteItems,
		commandPaletteActiveIndex: listState.commandPaletteActiveIndex,
		onCommandPaletteQueryChange: listState.onCommandPaletteQueryChange,
		setCommandPaletteActiveIndex: listState.setCommandPaletteActiveIndex,
		runCommandPaletteItem: listState.runCommandPaletteItem,
		closeCommandPalette: listState.closeCommandPalette,
		onCommandPaletteKeyDown: listState.onCommandPaletteKeyDown,
		globalSearchOpen: paneVm.globalSearchOpen,
		closeGlobalSearch: paneVm.closeGlobalSearch,
		globalSearchDraft: paneVm.globalSearchDraft,
		setGlobalSearchDraft: paneVm.setGlobalSearchDraft,
		globalSearchPrefix: paneVm.globalSearchPrefix,
		setGlobalSearchPrefix: paneVm.setGlobalSearchPrefix,
		globalSearchLimitClamped: paneVm.globalSearchLimitClamped,
		setGlobalSearchLimit: paneVm.setGlobalSearchLimit,
		globalSearchExt: paneVm.globalSearchExt,
		setGlobalSearchExt: paneVm.setGlobalSearchExt,
		globalSearchMinSize: paneVm.globalSearchMinSize,
		setGlobalSearchMinSize: paneVm.setGlobalSearchMinSize,
		globalSearchMaxSize: paneVm.globalSearchMaxSize,
		setGlobalSearchMaxSize: paneVm.setGlobalSearchMaxSize,
		globalSearchMinModifiedMs: paneVm.globalSearchMinModifiedMs,
		setGlobalSearchMinModifiedMs: paneVm.setGlobalSearchMinModifiedMs,
		globalSearchMaxModifiedMs: paneVm.globalSearchMaxModifiedMs,
		setGlobalSearchMaxModifiedMs: paneVm.setGlobalSearchMaxModifiedMs,
		resetGlobalSearch: paneVm.resetGlobalSearch,
		indexedSearchQuery: listVm.indexedSearchQuery,
		indexedSearchNotIndexed: listVm.indexedSearchNotIndexed,
		indexedSearchErrorMessage: listVm.indexedSearchErrorMessage,
		indexedSearchItems: listVm.indexedSearchItems,
		indexObjectsJobMutation: operationVm.indexObjectsJobMutation,
		indexPrefix: paneVm.indexPrefix,
		setIndexPrefix: paneVm.setIndexPrefix,
		indexFullReindex: paneVm.indexFullReindex,
		setIndexFullReindex: paneVm.setIndexFullReindex,
		globalSearchQueryText: listVm.globalSearchQueryText,
		onOpenPrefix: locationVm.onOpenPrefix,
		onCopy: listState.onCopy,
		onDownload: listState.onDownload,
		openGlobalSearchPrefix: listState.openGlobalSearchPrefix,
		openGlobalSearchDetails: listState.openGlobalSearchDetails,
	})
}
