import { buildObjectsPageOverlaysProps } from './buildObjectsPageOverlaysProps'
import type { ObjectsScreenArgs } from './objectsScreenTypes'
import type { ObjectsScreenListState } from './useObjectsScreenList'

type Args = Pick<ObjectsScreenArgs, 'props' | 'data' | 'actions'> & {
	listState: ObjectsScreenListState
}

export function useObjectsScreenOverlays({ props, data, actions, listState }: Args) {
	return buildObjectsPageOverlaysProps({
		actions,
		apiToken: props.apiToken,
		profileId: props.profileId,
		bucket: data.bucket,
		prefix: data.prefix,
		isMd: !!data.screens.md,
		bucketOptions: data.bucketOptions,
		bucketsLoading: data.bucketsQuery.isFetching,
		selectedCount: data.selectedCount,
		filtersDrawerOpen: data.filtersDrawerOpen,
		setFiltersDrawerOpen: data.setFiltersDrawerOpen,
		isAdvanced: data.isAdvanced,
		typeFilter: data.typeFilter,
		setTypeFilter: data.setTypeFilter,
		favoritesOnly: data.favoritesOnly,
		setFavoritesOnly: data.setFavoritesOnly,
		favoritesFirst: data.favoritesFirst,
		setFavoritesFirst: data.setFavoritesFirst,
		extFilter: data.extFilter,
		extOptions: data.extOptions,
		setExtFilter: data.setExtFilter,
		minSize: data.minSize,
		maxSize: data.maxSize,
		setMinSize: data.setMinSize,
		setMaxSize: data.setMaxSize,
		minModifiedMs: data.minModifiedMs,
		maxModifiedMs: data.maxModifiedMs,
		setMinModifiedMs: data.setMinModifiedMs,
		setMaxModifiedMs: data.setMaxModifiedMs,
		sort: data.sort,
		setSort: data.setSort,
		resetFilters: listState.resetFilters,
		hasActiveView: listState.hasActiveView,
		pathModalOpen: data.pathModalOpen,
		pathDraft: data.pathDraft,
		pathOptions: data.pathOptions,
		pathInputRef: data.pathInputRef,
		setPathDraft: data.setPathDraft,
		commitPathDraft: data.commitPathDraft,
		setPathModalOpen: data.setPathModalOpen,
		commandPaletteOpen: listState.commandPaletteOpen,
		commandPaletteQuery: listState.commandPaletteQuery,
		commandPaletteItems: listState.commandPaletteItems,
		commandPaletteActiveIndex: listState.commandPaletteActiveIndex,
		onCommandPaletteQueryChange: listState.onCommandPaletteQueryChange,
		setCommandPaletteActiveIndex: listState.setCommandPaletteActiveIndex,
		runCommandPaletteItem: listState.runCommandPaletteItem,
		closeCommandPalette: listState.closeCommandPalette,
		onCommandPaletteKeyDown: listState.onCommandPaletteKeyDown,
		globalSearchOpen: data.globalSearchOpen,
		closeGlobalSearch: data.closeGlobalSearch,
		globalSearchDraft: data.globalSearchDraft,
		setGlobalSearchDraft: data.setGlobalSearchDraft,
		globalSearchPrefix: data.globalSearchPrefix,
		setGlobalSearchPrefix: data.setGlobalSearchPrefix,
		globalSearchLimitClamped: data.globalSearchLimitClamped,
		setGlobalSearchLimit: data.setGlobalSearchLimit,
		globalSearchExt: data.globalSearchExt,
		setGlobalSearchExt: data.setGlobalSearchExt,
		globalSearchMinSize: data.globalSearchMinSize,
		setGlobalSearchMinSize: data.setGlobalSearchMinSize,
		globalSearchMaxSize: data.globalSearchMaxSize,
		setGlobalSearchMaxSize: data.setGlobalSearchMaxSize,
		globalSearchMinModifiedMs: data.globalSearchMinModifiedMs,
		setGlobalSearchMinModifiedMs: data.setGlobalSearchMinModifiedMs,
		globalSearchMaxModifiedMs: data.globalSearchMaxModifiedMs,
		setGlobalSearchMaxModifiedMs: data.setGlobalSearchMaxModifiedMs,
		resetGlobalSearch: data.resetGlobalSearch,
		indexedSearchQuery: data.indexedSearchQuery,
		indexedSearchNotIndexed: data.indexedSearchNotIndexed,
		indexedSearchErrorMessage: data.indexedSearchErrorMessage,
		indexedSearchItems: data.indexedSearchItems,
		indexObjectsJobMutation: data.indexObjectsJobMutation,
		indexPrefix: data.indexPrefix,
		setIndexPrefix: data.setIndexPrefix,
		indexFullReindex: data.indexFullReindex,
		setIndexFullReindex: data.setIndexFullReindex,
		globalSearchQueryText: data.globalSearchQueryText,
		onOpenPrefix: data.onOpenPrefix,
		onCopy: listState.onCopy,
		onDownload: listState.onDownload,
		openGlobalSearchPrefix: listState.openGlobalSearchPrefix,
		openGlobalSearchDetails: listState.openGlobalSearchDetails,
	})
}
