import {
	COMPACT_ROW_HEIGHT_PX,
	WIDE_ROW_HEIGHT_PX,
} from './objectsPageConstants'
import { logContextMenuDebug } from './objectsPageDebug'
import styles from './ObjectsListView.module.css'
import type {
	ObjectsListVm,
	ObjectsLocationVm,
	ObjectsOperationVm,
	ObjectsPaneVm,
	ObjectsScreenArgs,
	ObjectsSelectionVm,
} from './objectsScreenTypes'
import { useObjectsBreadcrumbItems } from './useObjectsBreadcrumbItems'
import { useObjectsGridRenderers } from './useObjectsGridRenderers'
import { useObjectsPageListInteractions } from './useObjectsPageListInteractions'
import type { ObjectsScreenListActionRuntime } from './useObjectsScreenListActionRuntime'

type UseObjectsScreenListRenderingArgs = Pick<ObjectsScreenArgs, 'props' | 'actions' | 'previewState' | 'viewportState' | 'refresh'> & {
	locationVm: ObjectsLocationVm
	listVm: ObjectsListVm
	selectionVm: ObjectsSelectionVm
	operationVm: ObjectsOperationVm
	paneVm: ObjectsPaneVm
	runtime: ObjectsScreenListActionRuntime
}

export function useObjectsScreenListRendering({
	props,
	locationVm,
	listVm,
	selectionVm,
	operationVm,
	paneVm,
	actions,
	previewState,
	viewportState,
	refresh,
	runtime,
}: UseObjectsScreenListRenderingArgs) {
	const {
		activeTabId,
		addTab,
		bucket,
		canGoBack,
		canGoForward,
		canGoUp,
		closeTab,
		goBack,
		goForward,
		navigateToLocation,
		onOpenPrefix,
		onUp,
		openPathModal,
		prefix,
		tabs,
	} = locationVm
	const {
		favoriteKeys,
		favoritePendingKeys,
		highlightText,
		isAdvanced,
		isCompactList,
		showThumbnails,
	} = listVm
	const {
		clearSelection,
		ensureObjectSelectedForContextMenu,
		selectObjectFromCheckboxEvent,
		selectObjectFromPointerEvent,
		selectedCount,
		selectedKeys,
	} = selectionVm
	const {
		api,
		commandPaletteOpener,
		debugContextMenu,
		isOffline,
		objectCrudSupported,
		profileCapabilities,
		selectedProfileProvider,
		thumbnailCache,
		toggleFavorite,
		transfers,
		uploadSupported,
		zipPrefixJobMutation,
	} = operationVm
	const {
		canDragDrop,
		detailsVisible,
		handleToggleUiMode,
		openGlobalSearch,
		screens,
		setTreeDrawerOpen,
	} = paneVm
	const {
		openDetailsForKey,
		openRenameObject,
		openRenamePrefix,
		openCopyMove,
		openCopyPrefix,
		openNewFolder,
		openDownloadPrefix,
		confirmDeleteObjects,
		confirmDeleteSelected,
		confirmDeletePrefixAsJob,
		openUploadPicker,
		toggleDetails,
	} = actions
	const { objectByKey, singleSelectedKey, singleSelectedItem } = previewState
	const { listScrollerEl, scrollContainerRef, measureElement } = viewportState
	const listGridClassName = isCompactList ? styles.listGridCompact : styles.listGridWide
	const scopeKey = `${props.apiToken || '__no_server__'}:${props.profileId?.trim() || '__no_profile__'}:${bucket}:${prefix}`

	const {
		getObjectActions,
		getPrefixActions,
		currentPrefixActionMap,
		selectionActionMap,
		selectionContextMenuActions,
		selectionMenuActions,
		globalActionMap,
		commandItems,
		closeContextMenu,
		contextMenuClassName,
		contextMenuState,
		contextMenuRef,
		contextMenuVisible,
		contextMenuProps,
		contextMenuStyle,
		getListScrollerElement,
		recordContextMenuPoint,
		openPrefixContextMenu,
		openObjectContextMenu,
		withContextMenuClassName,
		handleListScrollerContextMenu,
		handleListScrollerScroll,
		handleListScrollerWheel,
		renderPrefixRow,
		renderObjectRow,
		handleTreePrefixContextMenu,
	} = useObjectsPageListInteractions({
		actionCatalog: {
			isAdvanced,
			isOffline,
			profileId: props.profileId,
			bucket,
			prefix,
			objectCrudSupported,
			presignedDownloadSupported: profileCapabilities?.presignedUpload ?? false,
			uploadSupported,
			selectedCount,
			clipboardObjects: runtime.clipboardObjects,
			singleSelectedKey,
			singleSelectedItemSize: singleSelectedItem?.size,
			canGoBack,
			canGoForward,
			canGoUp,
			detailsVisible,
			activeTabId,
			tabsCount: tabs.length,
			onGoBack: goBack,
			onGoForward: goForward,
			onGoUp: onUp,
			onDownload: runtime.onDownload,
			onDownloadToDevice: runtime.onDownloadToDevice,
			onPresign: runtime.onPresign,
			onCopy: runtime.onCopy,
			onOpenLargePreviewForKey: previewState.openLargePreviewForKey,
			onOpenDetailsForKey: openDetailsForKey,
			onOpenRenameObject: openRenameObject,
			onOpenCopyMove: openCopyMove,
			onConfirmDeleteObjects: confirmDeleteObjects,
			onOpenPrefix,
			onOpenRenamePrefix: openRenamePrefix,
			onConfirmDeletePrefixAsJob: confirmDeletePrefixAsJob,
			onOpenCopyPrefix: openCopyPrefix,
			onOpenDownloadPrefix: openDownloadPrefix,
			onZipPrefix: (targetPrefix) => zipPrefixJobMutation.mutate({ prefix: targetPrefix }),
			onDownloadSelected: runtime.handleDownloadSelected,
			onOpenMoveSelected: actions.openMoveSelection,
			onCopySelectionToClipboard: (mode) => void runtime.copySelectionToClipboard(mode),
			onPasteClipboardObjects: () => void runtime.pasteClipboardObjects(),
			onClearSelection: clearSelection,
			onConfirmDeleteSelected: confirmDeleteSelected,
			onToggleDetails: toggleDetails,
			onOpenTreeDrawer: () => setTreeDrawerOpen(true),
			onRefresh: () => void refresh(),
			onOpenPathModal: openPathModal,
			onOpenUpload: openUploadPicker,
			onOpenNewFolder: openNewFolder,
			onOpenCommandPalette: commandPaletteOpener.open,
			onOpenTransfers: () => transfers.openTransfers(),
			onAddTab: addTab,
			onCloseTab: closeTab,
			onOpenGlobalSearch: openGlobalSearch,
			onToggleUiMode: handleToggleUiMode,
		},
		contextMenu: {
			scopeKey,
			debugEnabled: debugContextMenu,
			log: logContextMenuDebug,
			listScrollerEl,
			scrollContainerRef,
			selectedCount,
			objectByKey,
			selectedKeys,
			isAdvanced,
			ensureObjectSelected: ensureObjectSelectedForContextMenu,
		},
		rowRenderers: {
			api,
			apiToken: props.apiToken,
			profileId: props.profileId,
			profileProvider: selectedProfileProvider,
			bucket,
			prefix,
			canDragDrop,
			isCompactList,
			isAdvanced,
			isOffline,
			objectCrudSupported,
			listGridClassName,
			rowHeightCompactPx: COMPACT_ROW_HEIGHT_PX,
			rowHeightWidePx: WIDE_ROW_HEIGHT_PX,
			measureElement,
			showThumbnails,
			thumbnailCache,
			highlightText,
			onOpenPrefix,
			onRowDragStartPrefix: runtime.onRowDragStartPrefix,
			onRowDragStartObjects: runtime.onRowDragStartObjects,
			dndHoverPrefix: runtime.dndHoverPrefix,
			normalizeDropTargetPrefix: runtime.normalizeDropTargetPrefix,
			onDndTargetDragOver: runtime.onDndTargetDragOver,
			onDndTargetDragLeave: runtime.onDndTargetDragLeave,
			onDndTargetDrop: runtime.onDndTargetDrop,
			clearDndHover: runtime.clearDndHover,
			selectObjectFromPointerEvent,
			selectObjectFromCheckboxEvent,
			onOpenLargePreviewForKey: previewState.openLargePreviewForKey,
			selectedCount,
			selectedKeys,
			favoriteKeys,
			favoritePendingKeys,
			toggleFavorite,
		},
	})

	const { renderPrefixGridItem, renderObjectGridItem } = useObjectsGridRenderers({
		api,
		apiToken: props.apiToken,
		profileId: props.profileId,
		profileProvider: selectedProfileProvider,
		bucket,
		prefix,
		canDragDrop,
		isAdvanced,
		isOffline,
		objectCrudSupported,
		showThumbnails,
		thumbnailCache,
		highlightText,
		contextMenuState,
		withContextMenuClassName,
		getPrefixActions,
		getObjectActions,
		selectionContextMenuActions,
		recordContextMenuPoint,
		openPrefixContextMenu,
		openObjectContextMenu,
		closeContextMenu,
		onOpenPrefix,
		onOpenLargePreviewForKey: previewState.openLargePreviewForKey,
		onRowDragStartPrefix: runtime.onRowDragStartPrefix,
		onRowDragStartObjects: runtime.onRowDragStartObjects,
		dndHoverPrefix: runtime.dndHoverPrefix,
		normalizeDropTargetPrefix: runtime.normalizeDropTargetPrefix,
		onDndTargetDragOver: runtime.onDndTargetDragOver,
		onDndTargetDragLeave: runtime.onDndTargetDragLeave,
		onDndTargetDrop: runtime.onDndTargetDrop,
		clearDndHover: runtime.clearDndHover,
		selectObjectFromPointerEvent,
		selectObjectFromCheckboxEvent,
		selectedCount,
		selectedKeys,
		favoriteKeys,
		favoritePendingKeys,
		toggleFavorite,
	})

	const { breadcrumbItems } = useObjectsBreadcrumbItems({
		scopeKey,
		bucket,
		prefix,
		isMd: !!screens.md,
		canDragDrop,
		dndHoverPrefix: runtime.dndHoverPrefix,
		normalizeDropTargetPrefix: runtime.normalizeDropTargetPrefix,
		onDndTargetDragOver: runtime.onDndTargetDragOver,
		onDndTargetDragLeave: runtime.onDndTargetDragLeave,
		onDndTargetDrop: runtime.onDndTargetDrop,
		navigateToLocation,
	})

	return {
		breadcrumbItems,
		closeContextMenu,
		commandItems,
		contextMenuClassName,
		contextMenuProps,
		contextMenuRef,
		contextMenuState,
		contextMenuStyle,
		contextMenuVisible,
		currentPrefixActionMap,
		getListScrollerElement,
		getObjectActions,
		getPrefixActions,
		globalActionMap,
		handleListScrollerContextMenu,
		handleListScrollerScroll,
		handleListScrollerWheel,
		handleTreePrefixContextMenu,
		listGridClassName,
		renderObjectGridItem,
		renderObjectRow,
		renderPrefixGridItem,
		renderPrefixRow,
		selectionActionMap,
		selectionMenuActions,
	}
}
