import { formatErrorWithHint as formatErr } from '../../lib/errors'
import { buildObjectsPagePanesProps } from './buildObjectsPagePanesProps'
import type { ObjectsScreenArgs } from './objectsScreenTypes'
import { useObjectsScreenList } from './useObjectsScreenList'
import { useObjectsScreenOverlays } from './useObjectsScreenOverlays'
import { useObjectsScreenToolbar } from './useObjectsScreenToolbar'

export function useObjectsScreenComposition({ props, data, actions, previewState, viewportState, refresh }: ObjectsScreenArgs) {
	const listState = useObjectsScreenList({ props, data, actions, previewState, viewportState, refresh })
	const { toolbarSectionProps, canCreateFolder, createFolderTooltipText } = useObjectsScreenToolbar({
		props,
		data,
		actions,
		refresh,
		listState,
	})
	const overlaysProps = useObjectsScreenOverlays({ props, data, actions, listState })

	const panesProps = buildObjectsPagePanesProps({
		profileId: props.profileId,
		bucket: data.bucket,
		prefix: data.prefix,
		layoutProps: {
			treeWidthPx: data.dockTree ? data.treeWidthUsed : 0,
			treeHandleWidthPx: data.treeResizeHandleWidth,
			detailsWidthPx: data.dockDetails ? data.detailsWidthUsed : 0,
			detailsHandleWidthPx: data.dockDetails && data.detailsOpen ? data.detailsResizeHandleWidth : 0,
			treeDocked: data.dockTree,
			detailsDocked: data.dockDetails,
			detailsOpen: data.detailsOpen,
		},
		contextMenuPortalProps: {
			contextMenuClassName: listState.contextMenuClassName,
			contextMenuRef: listState.contextMenuRef,
			contextMenuVisible: listState.contextMenuVisible,
			contextMenuProps: listState.contextMenuProps,
			contextMenuStyle: listState.contextMenuStyle,
		},
		treeDrawerOpen: data.treeDrawerOpen,
		dockTree: data.dockTree,
		favoriteItems: data.favoriteItems,
		favoritesSearch: data.favoritesSearch,
		setFavoritesSearch: data.setFavoritesSearch,
		favoritesOnly: data.favoritesOnly,
		setFavoritesOnly: data.setFavoritesOnly,
		favoritesOpenDetails: data.favoritesOpenDetails,
		setFavoritesOpenDetails: data.setFavoritesOpenDetails,
		handleFavoriteSelect: actions.handleFavoriteSelect,
		favoritesLoading: data.favoritesQuery.isFetching,
		favoritesErrorMessage: data.favoritesQuery.isError ? formatErr(data.favoritesQuery.error) : null,
		treeData: data.treeData,
		treeLoadingKeys: data.treeLoadingKeys,
		onTreeLoadData: data.onTreeLoadData,
		treeSelectedKeys: data.treeSelectedKeys,
		treeExpandedKeys: data.treeExpandedKeys,
		setTreeExpandedKeys: data.setTreeExpandedKeys,
		handleTreeSelect: data.handleTreeSelect,
		normalizeDropTargetPrefix: listState.normalizeDropTargetPrefix,
		canDragDrop: data.canDragDrop,
		dndHoverPrefix: listState.dndHoverPrefix,
		onDndTargetDragOver: listState.onDndTargetDragOver,
		onDndTargetDragLeave: listState.onDndTargetDragLeave,
		onDndTargetDrop: listState.onDndTargetDrop,
		onTreeResizePointerDown: data.onTreeResizePointerDown,
		onTreeResizePointerMove: data.onTreeResizePointerMove,
		onTreeResizePointerUp: data.onTreeResizePointerUp,
		canCreateFolder,
		createFolderTooltipText,
		openNewFolder: actions.openNewFolder,
		handleTreePrefixContextMenu: listState.handleTreePrefixContextMenu,
		setTreeDrawerOpen: data.setTreeDrawerOpen,
		isBookmarked: data.isBookmarked,
		toggleBookmark: data.toggleBookmark,
		openPathModal: data.openPathModal,
		breadcrumbItems: listState.breadcrumbItems,
		isCompactList: data.isCompactList,
		searchDraft: data.searchDraft,
		setSearchDraft: data.setSearchDraft,
		hasActiveView: listState.hasActiveView,
		setFiltersDrawerOpen: data.setFiltersDrawerOpen,
		isAdvanced: data.isAdvanced,
		visiblePrefixCount: data.visiblePrefixCount,
		visibleFileCount: data.visibleFileCount,
		search: data.search,
		objectsHasNextPage: data.objectsQuery.hasNextPage ?? false,
		objectsIsFetchingNextPage: data.objectsQuery.isFetchingNextPage,
		rawTotalCount: data.rawTotalCount,
		searchAutoScanCap: listState.searchAutoScanCap,
		openGlobalSearch: data.openGlobalSearch,
		setUiMode: data.setUiMode,
		canInteract: listState.canInteract,
		sort: data.sort,
		setSort: data.setSort,
		favoritesFirst: data.favoritesFirst,
		setFavoritesFirst: data.setFavoritesFirst,
		viewMode: data.viewMode,
		setViewMode: data.setViewMode,
		isOffline: data.isOffline,
		objectsErrorMessage: data.objectsQuery.isError ? formatErr(data.objectsQuery.error) : null,
		uploadDropActive: listState.showUploadDropOverlay,
		uploadDropLabel: listState.uploadDropLabel,
		onUploadDragEnter: listState.onUploadDragEnter,
		onUploadDragLeave: listState.onUploadDragLeave,
		onUploadDragOver: listState.onUploadDragOver,
		onUploadDrop: listState.onUploadDrop,
		selectedCount: data.selectedCount,
		singleSelectedKey: previewState.singleSelectedKey,
		singleSelectedSize: previewState.singleSelectedItem?.size,
		clearSelectionAction: listState.clearSelectionAction,
		deleteSelectionAction: listState.deleteSelectionAction,
		downloadSelectionAction: listState.downloadSelectionAction,
		selectionMenuActions: listState.selectionMenuActions,
		getObjectActions: listState.getObjectActions,
		isDownloadLoading: data.zipObjectsJobMutation.isPending,
		isDeleteLoading: actions.deleteMutation.isPending && actions.deletingKey === null,
		listGridClassName: listState.listGridClassName,
		allLoadedSelected: data.allLoadedSelected,
		someLoadedSelected: data.someLoadedSelected,
		visibleObjectKeys: data.visibleObjectKeys,
		handleToggleSelectAll: data.handleToggleSelectAll,
		sortDirForColumn: listState.sortDirForColumn,
		toggleSortColumn: listState.toggleSortColumn,
		listScrollerRef: listState.listScrollerRef,
		getListScrollerElement: listState.getListScrollerElement,
		listKeydownHandler: listState.listKeydownHandler,
		handleListScrollerScroll: listState.handleListScrollerScroll,
		handleListScrollerWheel: listState.handleListScrollerWheel,
		handleListScrollerContextMenu: listState.handleListScrollerContextMenu,
		rows: data.rows,
		virtualItemsForRender: viewportState.virtualItemsForRender,
		totalSize: viewportState.totalSize,
		listIsFetching: listState.listIsFetching,
		listIsFetchingNextPage: listState.listIsFetchingNextPage,
		emptyKind: data.emptyKind,
		canClearSearch: listState.canClearSearch,
		handleClearSearch: listState.handleClearSearch,
		renderPrefixRow: listState.renderPrefixRow,
		renderObjectRow: listState.renderObjectRow,
		renderPrefixGridItem: listState.renderPrefixGridItem,
		renderObjectGridItem: listState.renderObjectGridItem,
		showLoadMore: listState.showLoadMore,
		loadMoreLabel: listState.loadMoreLabel,
		loadMoreDisabled: listState.loadMoreDisabled,
		handleLoadMore: listState.handleLoadMore,
		detailsKey: listState.detailsKey,
		detailsMeta: listState.detailsMeta,
		detailsMetaQueryIsFetching: listState.detailsMetaQuery.isFetching,
		detailsMetaQueryIsError: listState.detailsMetaQuery.isError,
		detailsMetaErrorMessage: listState.detailsMetaQuery.isError ? formatErr(listState.detailsMetaQuery.error) : '',
		refetchDetailsMeta: listState.refetchDetailsMeta,
		onCopy: listState.onCopy,
		onDownload: listState.onDownload,
		presignMutate: listState.onPresign,
		presignPendingForKey: listState.presignPendingForKey,
		openCopyMove: listState.openCopyMove,
		confirmDeleteObjects: listState.confirmDeleteObjects,
		detailsDeleteLoading: listState.detailsDeleteLoading,
		detailsThumbnail: listState.detailsThumbnail,
		detailsPreviewThumbnail: listState.detailsPreviewThumbnail,
		preview: listState.preview,
		loadPreview: listState.loadPreview,
		cancelPreview: listState.cancelPreview,
		canCancelPreview: listState.canCancelPreview,
		openLargePreview: () => {
			if (!listState.detailsKey) return
			previewState.openLargePreviewForKey(listState.detailsKey)
		},
		dockDetails: data.dockDetails,
		detailsOpen: data.detailsOpen,
		detailsDrawerOpen: data.detailsDrawerOpen,
		openDetails: listState.openDetails,
		setDetailsOpen: data.setDetailsOpen,
		setDetailsDrawerOpen: data.setDetailsDrawerOpen,
		onDetailsResizePointerDown: data.onDetailsResizePointerDown,
		onDetailsResizePointerMove: data.onDetailsResizePointerMove,
		onDetailsResizePointerUp: data.onDetailsResizePointerUp,
	})

	return {
		toolbarSectionProps,
		onDownload: listState.onDownload,
		onPresign: listState.onPresign,
		overlaysProps,
		panesProps,
	}
}
