import type { UseObjectsGridRenderersArgs } from './objectsGridRendererTypes'
import { useObjectsObjectGridRenderer } from './useObjectsObjectGridRenderer'
import { useObjectsPrefixGridRenderer } from './useObjectsPrefixGridRenderer'

export function useObjectsGridRenderers({
	api,
	profileId,
	bucket,
	prefix,
	canDragDrop,
	isAdvanced,
	isOffline,
	showThumbnails,
	thumbnailCache,
	highlightText,
	contextMenuState,
	withContextMenuClassName,
	getPrefixActions,
	getObjectActions,
	selectionContextMenuActions,
	recordContextMenuPoint,
	openPrefixContextMenu,
	openObjectContextMenu,
	closeContextMenu,
	onOpenPrefix,
	onOpenLargePreviewForKey,
	onRowDragStartPrefix,
	onRowDragStartObjects,
	clearDndHover,
	selectObjectFromPointerEvent,
	selectObjectFromCheckboxEvent,
	selectedCount,
	selectedKeys,
	favoriteKeys,
	favoritePendingKeys,
	toggleFavorite,
}: UseObjectsGridRenderersArgs) {
	const renderPrefixGridItem = useObjectsPrefixGridRenderer({
		canDragDrop,
		isAdvanced,
		highlightText,
		contextMenuState,
		withContextMenuClassName,
		getPrefixActions,
		recordContextMenuPoint,
		openPrefixContextMenu,
		closeContextMenu,
		onOpenPrefix,
		onRowDragStartPrefix,
		clearDndHover,
		prefix,
	})

	const renderObjectGridItem = useObjectsObjectGridRenderer({
		api,
		profileId,
		bucket,
		prefix,
		canDragDrop,
		isAdvanced,
		isOffline,
		showThumbnails,
		thumbnailCache,
		highlightText,
		contextMenuState,
		withContextMenuClassName,
		getObjectActions,
		selectionContextMenuActions,
		recordContextMenuPoint,
		openObjectContextMenu,
		closeContextMenu,
		onOpenLargePreviewForKey,
		onRowDragStartObjects,
		clearDndHover,
		selectObjectFromPointerEvent,
		selectObjectFromCheckboxEvent,
		selectedCount,
		selectedKeys,
		favoriteKeys,
		favoritePendingKeys,
		toggleFavorite,
	})

	return {
		renderPrefixGridItem,
		renderObjectGridItem,
	}
}
