import { formatErrorWithHint as formatErr } from '../../lib/errors'
import { buildObjectsPagePanesProps } from './buildObjectsPagePanesProps'
import type {
	ObjectsListVm,
	ObjectsLocationVm,
	ObjectsOperationVm,
	ObjectsPaneVm,
	ObjectsScreenArgs,
	ObjectsSelectionVm,
} from './objectsScreenTypes'
import type { ObjectsScreenListState } from './useObjectsScreenList'

type UseObjectsScreenPanesArgs = Pick<ObjectsScreenArgs, 'props' | 'actions' | 'previewState' | 'viewportState'> & {
	locationVm: ObjectsLocationVm
	listVm: ObjectsListVm
	selectionVm: ObjectsSelectionVm
	operationVm: ObjectsOperationVm
	paneVm: ObjectsPaneVm
	listState: ObjectsScreenListState
	canCreateFolder: boolean
	createFolderTooltipText: string
}

export function useObjectsScreenPanes({
	props,
	locationVm,
	listVm,
	selectionVm,
	operationVm,
	paneVm,
	actions,
	previewState,
	viewportState,
	listState,
	canCreateFolder,
	createFolderTooltipText,
}: UseObjectsScreenPanesArgs) {
	return buildObjectsPagePanesProps({
		profileId: props.profileId,
		bucket: locationVm.bucket,
		prefix: locationVm.prefix,
		layoutProps: {
			treeWidthPx: paneVm.dockTree ? paneVm.treeWidthUsed : 0,
			treeHandleWidthPx: paneVm.treeResizeHandleWidth,
			detailsWidthPx: paneVm.dockDetails ? paneVm.detailsWidthUsed : 0,
			detailsHandleWidthPx: paneVm.dockDetails && paneVm.detailsOpen ? paneVm.detailsResizeHandleWidth : 0,
			treeDocked: paneVm.dockTree,
			detailsDocked: paneVm.dockDetails,
			detailsOpen: paneVm.detailsOpen,
		},
		contextMenuPortalProps: {
			contextMenuClassName: listState.contextMenuClassName,
			contextMenuRef: listState.contextMenuRef,
			contextMenuVisible: listState.contextMenuVisible,
			contextMenuProps: listState.contextMenuProps,
			contextMenuStyle: listState.contextMenuStyle,
		},
		treeDrawerOpen: paneVm.treeDrawerOpen,
		dockTree: paneVm.dockTree,
		favoriteItems: listVm.favoriteItems,
		favoriteCount: paneVm.favoriteCount,
		favoritesSearch: paneVm.favoritesSearch,
		setFavoritesSearch: paneVm.setFavoritesSearch,
		favoritesOnly: listVm.favoritesOnly,
		setFavoritesOnly: listVm.setFavoritesOnly,
		favoritesOpenDetails: paneVm.favoritesOpenDetails,
		setFavoritesOpenDetails: paneVm.setFavoritesOpenDetails,
		favoritesPaneExpanded: paneVm.favoritesPaneExpanded,
		setFavoritesPaneExpanded: paneVm.setFavoritesPaneExpanded,
		handleFavoriteSelect: actions.handleFavoriteSelect,
		favoritesLoading: listVm.favoritesQuery.isFetching,
		favoritesErrorMessage: listVm.favoritesQuery.isError ? formatErr(listVm.favoritesQuery.error) : null,
		treeData: paneVm.treeData,
		treeErrorMessage: paneVm.treeErrorMessage,
		treeLoadingKeys: paneVm.treeLoadingKeys,
		onTreeLoadData: paneVm.onTreeLoadData,
		treeSelectedKeys: paneVm.treeSelectedKeys,
		treeExpandedKeys: paneVm.treeExpandedKeys,
		setTreeExpandedKeys: paneVm.setTreeExpandedKeys,
		handleTreeSelect: paneVm.handleTreeSelect,
		normalizeDropTargetPrefix: listState.normalizeDropTargetPrefix,
		canDragDrop: paneVm.canDragDrop,
		dndHoverPrefix: listState.dndHoverPrefix,
		onDndTargetDragOver: listState.onDndTargetDragOver,
		onDndTargetDragLeave: listState.onDndTargetDragLeave,
		onDndTargetDrop: listState.onDndTargetDrop,
		onTreeResizePointerDown: paneVm.onTreeResizePointerDown,
		onTreeResizePointerMove: paneVm.onTreeResizePointerMove,
		onTreeResizePointerUp: paneVm.onTreeResizePointerUp,
		onTreeResizeKeyDown: paneVm.onTreeResizeKeyDown,
		treeResizeMinWidth: paneVm.treeResizeMinWidth,
		treeResizeMaxWidth: paneVm.treeResizeMaxWidth,
		treeWidthUsed: paneVm.treeWidthUsed,
		canCreateFolder,
		createFolderTooltipText,
		openNewFolder: actions.openNewFolder,
		handleTreePrefixContextMenu: listState.handleTreePrefixContextMenu,
		setTreeDrawerOpen: paneVm.setTreeDrawerOpen,
		isBookmarked: locationVm.isBookmarked,
		toggleBookmark: locationVm.toggleBookmark,
		openPathModal: locationVm.openPathModal,
		breadcrumbItems: listState.breadcrumbItems,
		isCompactList: listVm.isCompactList,
		searchDraft: listVm.searchDraft,
		setSearchDraft: listVm.setSearchDraft,
		hasActiveView: listState.hasActiveView,
		setFiltersDrawerOpen: paneVm.setFiltersDrawerOpen,
		isAdvanced: listVm.isAdvanced,
		visiblePrefixCount: listVm.visiblePrefixCount,
		visibleFileCount: listVm.visibleFileCount,
		search: listVm.search,
		objectsHasNextPage: listVm.objectsQuery.hasNextPage ?? false,
		objectsIsFetchingNextPage: listVm.objectsQuery.isFetchingNextPage,
		rawTotalCount: listVm.rawTotalCount,
		searchAutoScanCap: listState.searchAutoScanCap,
		openGlobalSearch: paneVm.openGlobalSearch,
		setUiMode: paneVm.setUiMode,
		canInteract: listState.canInteract,
		sort: listVm.sort,
		setSort: listVm.setSort,
		favoritesFirst: listVm.favoritesFirst,
		setFavoritesFirst: listVm.setFavoritesFirst,
		viewMode: listVm.viewMode,
		setViewMode: listVm.setViewMode,
		isOffline: operationVm.isOffline,
		objectsErrorMessage: listVm.objectsQuery.isError ? formatErr(listVm.objectsQuery.error) : null,
		uploadDropActive: listState.showUploadDropOverlay,
		uploadDropLabel: listState.uploadDropLabel,
		onUploadDragEnter: listState.onUploadDragEnter,
		onUploadDragLeave: listState.onUploadDragLeave,
		onUploadDragOver: listState.onUploadDragOver,
		onUploadDrop: listState.onUploadDrop,
		selectedCount: selectionVm.selectedCount,
		singleSelectedKey: previewState.singleSelectedKey,
		singleSelectedSize: previewState.singleSelectedItem?.size,
		openMoveSelection: actions.openMoveSelection,
		clearSelectionAction: listState.clearSelectionAction,
		deleteSelectionAction: listState.deleteSelectionAction,
		downloadSelectionAction: listState.downloadSelectionAction,
		moveSelectionAction: listState.moveSelectionAction,
		selectionMenuActions: listState.selectionMenuActions,
		getObjectActions: listState.getObjectActions,
		isDownloadLoading: operationVm.zipObjectsJobMutation.isPending,
		isDeleteLoading: actions.deleteMutation.isPending && actions.deletingKey === null,
		listGridClassName: listState.listGridClassName,
		allLoadedSelected: listVm.allLoadedSelected,
		someLoadedSelected: listVm.someLoadedSelected,
		visibleObjectKeys: listVm.visibleObjectKeys,
		handleToggleSelectAll: selectionVm.handleToggleSelectAll,
		sortDirForColumn: listState.sortDirForColumn,
		toggleSortColumn: listState.toggleSortColumn,
		listScrollerRef: listState.listScrollerRef,
		getListScrollerElement: listState.getListScrollerElement,
		listKeydownHandler: listState.listKeydownHandler,
		handleListScrollerScroll: listState.handleListScrollerScroll,
		handleListScrollerWheel: listState.handleListScrollerWheel,
		handleListScrollerContextMenu: listState.handleListScrollerContextMenu,
		rows: listVm.rows,
		virtualItemsForRender: viewportState.virtualItemsForRender,
		totalSize: viewportState.totalSize,
		listIsFetching: listState.listIsFetching,
		listIsFetchingNextPage: listState.listIsFetchingNextPage,
		emptyKind: listVm.emptyKind,
		canClearSearch: listState.canClearSearch,
		handleClearSearch: listState.handleClearSearch,
		renderPrefixRow: listState.renderPrefixRow,
		renderObjectRow: listState.renderObjectRow,
		renderPrefixGridItem: listState.renderPrefixGridItem,
		renderObjectGridItem: listState.renderObjectGridItem,
		showLoadMore: listState.showLoadMore,
		loadMoreLabel: listState.loadMoreLabel,
		loadMoreDisabled: listState.loadMoreDisabled,
		handleLoadMore: listState.handleLoadMore,
		detailsKey: listState.detailsKey,
		detailsMeta: listState.detailsMeta,
		detailsMetaQueryIsFetching: listState.detailsMetaQuery.isFetching,
		detailsMetaQueryIsError: listState.detailsMetaQuery.isError,
		detailsMetaErrorMessage: listState.detailsMetaQuery.isError ? formatErr(listState.detailsMetaQuery.error) : '',
		refetchDetailsMeta: listState.refetchDetailsMeta,
		onCopy: listState.onCopy,
		onDownload: listState.onDownload,
		presignedDownloadSupported: operationVm.profileCapabilities?.presignedUpload ?? false,
		presignMutate: listState.onPresign,
		presignPendingForKey: listState.presignPendingForKey,
		openCopyMove: listState.openCopyMove,
		confirmDeleteObjects: listState.confirmDeleteObjects,
		detailsDeleteLoading: listState.detailsDeleteLoading,
		detailsThumbnail: listState.detailsThumbnail,
		detailsPreviewThumbnail: listState.detailsPreviewThumbnail,
		preview: listState.preview,
		loadPreview: listState.loadPreview,
		cancelPreview: listState.cancelPreview,
		canCancelPreview: listState.canCancelPreview,
		openLargePreview: () => {
			if (!listState.detailsKey) return
			previewState.openLargePreviewForKey(listState.detailsKey)
		},
		dockDetails: paneVm.dockDetails,
		detailsOpen: paneVm.detailsOpen,
		detailsDrawerOpen: paneVm.detailsDrawerOpen,
		detailsDrawerSuspended: previewState.largePreviewOpen,
		openDetails: listState.openDetails,
		setDetailsOpen: paneVm.setDetailsOpen,
		setDetailsDrawerOpen: paneVm.setDetailsDrawerOpen,
		onDetailsResizePointerDown: paneVm.onDetailsResizePointerDown,
		onDetailsResizePointerMove: paneVm.onDetailsResizePointerMove,
		onDetailsResizePointerUp: paneVm.onDetailsResizePointerUp,
		onDetailsResizeKeyDown: paneVm.onDetailsResizeKeyDown,
		detailsResizeMinWidth: paneVm.detailsResizeMinWidth,
		detailsResizeMaxWidth: paneVm.detailsResizeMaxWidth,
		detailsWidthUsed: paneVm.detailsWidthUsed,
	})
}
