#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_STACK="${COMPOSE_STACK:-portable-smoke}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-s3desk-portable-smoke}"
KEEP_UP="${KEEP_UP:-0}"
PORTABLE_SMOKE_SOURCE_DB_BACKEND="${PORTABLE_SMOKE_SOURCE_DB_BACKEND:-sqlite}"
PORTABLE_SMOKE_TARGET_DB_BACKEND="${PORTABLE_SMOKE_TARGET_DB_BACKEND:-postgres}"
DEFAULT_PORTABLE_ENCRYPTION_KEY="QkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkI="
PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY="${PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY:-${PORTABLE_SMOKE_ENCRYPTION_KEY:-$DEFAULT_PORTABLE_ENCRYPTION_KEY}}"
PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY="${PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY:-${PORTABLE_SMOKE_ENCRYPTION_KEY:-$DEFAULT_PORTABLE_ENCRYPTION_KEY}}"
PORTABLE_BUNDLE_PASSWORD="${PORTABLE_BUNDLE_PASSWORD:-}"
PORTABLE_BUNDLE_EXPORT_PASSWORD="${PORTABLE_BUNDLE_EXPORT_PASSWORD:-$PORTABLE_BUNDLE_PASSWORD}"
PORTABLE_BUNDLE_IMPORT_PASSWORD="${PORTABLE_BUNDLE_IMPORT_PASSWORD:-$PORTABLE_BUNDLE_PASSWORD}"
PORTABLE_BUNDLE_CONFIDENTIALITY="${PORTABLE_BUNDLE_CONFIDENTIALITY:-clear}"

compose() {
	COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME}" \
	PORTABLE_SMOKE_SOURCE_DB_BACKEND="${PORTABLE_SMOKE_SOURCE_DB_BACKEND}" \
	PORTABLE_SMOKE_TARGET_DB_BACKEND="${PORTABLE_SMOKE_TARGET_DB_BACKEND}" \
	PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY="${PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY}" \
	PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY="${PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY}" \
	PORTABLE_BUNDLE_CONFIDENTIALITY="${PORTABLE_BUNDLE_CONFIDENTIALITY}" \
	PORTABLE_BUNDLE_PASSWORD="${PORTABLE_BUNDLE_PASSWORD}" \
	PORTABLE_BUNDLE_EXPORT_PASSWORD="${PORTABLE_BUNDLE_EXPORT_PASSWORD}" \
	PORTABLE_BUNDLE_IMPORT_PASSWORD="${PORTABLE_BUNDLE_IMPORT_PASSWORD}" \
	"${ROOT_DIR}/scripts/compose.sh" "${COMPOSE_STACK}" "$@"
}

cleanup() {
	if [ "${KEEP_UP}" != "1" ]; then
		compose down -v --remove-orphans >/dev/null 2>&1 || true
	fi
}
trap cleanup EXIT

echo "[portable-smoke] preparing stack"
compose down -v --remove-orphans >/dev/null 2>&1 || true
compose up -d --build minio postgres source target

echo "[portable-smoke] seeding MinIO"
compose run --rm minio-seed

echo "[portable-smoke] seeding ${PORTABLE_SMOKE_SOURCE_DB_BACKEND} source fixture"
compose run --rm source-seed

echo "[portable-smoke] verifying ${PORTABLE_SMOKE_SOURCE_DB_BACKEND} -> ${PORTABLE_SMOKE_TARGET_DB_BACKEND} portable import"
compose run --rm portable-smoke

echo "[portable-smoke] success"
