#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_STACK="${COMPOSE_STACK:-portable-smoke}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-s3desk-portable-failure}"
KEEP_UP="${KEEP_UP:-0}"
PORTABLE_SMOKE_SOURCE_DB_BACKEND="${PORTABLE_SMOKE_SOURCE_DB_BACKEND:-sqlite}"
PORTABLE_SMOKE_TARGET_DB_BACKEND="${PORTABLE_SMOKE_TARGET_DB_BACKEND:-postgres}"
PORTABLE_SMOKE_BASE_ENCRYPTION_KEY="${PORTABLE_SMOKE_BASE_ENCRYPTION_KEY:-QkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkI=}"
PORTABLE_SMOKE_MISMATCH_ENCRYPTION_KEY="${PORTABLE_SMOKE_MISMATCH_ENCRYPTION_KEY:-Q0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0M=}"
PORTABLE_SMOKE_EXPORT_PASSWORD="${PORTABLE_SMOKE_EXPORT_PASSWORD:-operator-secret}"
PORTABLE_SMOKE_WRONG_IMPORT_PASSWORD="${PORTABLE_SMOKE_WRONG_IMPORT_PASSWORD:-wrong-secret}"
PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY="${PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY:-$PORTABLE_SMOKE_BASE_ENCRYPTION_KEY}"
PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY="${PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY:-$PORTABLE_SMOKE_BASE_ENCRYPTION_KEY}"

compose() {
	COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME}" \
	PORTABLE_SMOKE_SOURCE_DB_BACKEND="${PORTABLE_SMOKE_SOURCE_DB_BACKEND}" \
	PORTABLE_SMOKE_TARGET_DB_BACKEND="${PORTABLE_SMOKE_TARGET_DB_BACKEND}" \
	PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY="${PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY}" \
	PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY="${PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY}" \
	"${ROOT_DIR}/scripts/compose.sh" "${COMPOSE_STACK}" "$@"
}

cleanup() {
	if [ "${KEEP_UP}" != "1" ]; then
		compose down -v --remove-orphans >/dev/null 2>&1 || true
	fi
}
trap cleanup EXIT

bring_up_and_seed() {
	echo "[portable-failure] preparing ${PORTABLE_SMOKE_SOURCE_DB_BACKEND} -> ${PORTABLE_SMOKE_TARGET_DB_BACKEND} stack"
	compose down -v --remove-orphans >/dev/null 2>&1 || true
	compose up -d --build minio postgres source target

	echo "[portable-failure] seeding MinIO"
	compose run --rm minio-seed

	echo "[portable-failure] seeding ${PORTABLE_SMOKE_SOURCE_DB_BACKEND} source fixture"
	compose run --rm source-seed
}

run_failure() {
	local scenario="$1"
	shift
	echo "[portable-failure] scenario ${scenario}"
	compose run --rm \
		-e PORTABLE_FAILURE_SCENARIO="${scenario}" \
		"$@" \
		portable-smoke-failure
}

PORTABLE_SMOKE_SOURCE_ENCRYPTION_KEY="${PORTABLE_SMOKE_BASE_ENCRYPTION_KEY}"
PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY="${PORTABLE_SMOKE_BASE_ENCRYPTION_KEY}"
bring_up_and_seed
run_failure wrong_password \
	-e PORTABLE_BUNDLE_CONFIDENTIALITY=encrypted \
	-e PORTABLE_BUNDLE_EXPORT_PASSWORD="${PORTABLE_SMOKE_EXPORT_PASSWORD}" \
	-e PORTABLE_BUNDLE_IMPORT_PASSWORD="${PORTABLE_SMOKE_WRONG_IMPORT_PASSWORD}"
run_failure asset_copy_warning \
	-e PORTABLE_BUNDLE_CONFIDENTIALITY=clear \
	-e PORTABLE_BUNDLE_EXPORT_PASSWORD= \
	-e PORTABLE_BUNDLE_IMPORT_PASSWORD=

PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY="${PORTABLE_SMOKE_MISMATCH_ENCRYPTION_KEY}"
bring_up_and_seed
run_failure key_mismatch \
	-e PORTABLE_BUNDLE_CONFIDENTIALITY=clear \
	-e PORTABLE_BUNDLE_EXPORT_PASSWORD= \
	-e PORTABLE_BUNDLE_IMPORT_PASSWORD=

PORTABLE_SMOKE_TARGET_ENCRYPTION_KEY=""
bring_up_and_seed
run_failure preflight_blocker \
	-e PORTABLE_BUNDLE_CONFIDENTIALITY=clear \
	-e PORTABLE_BUNDLE_EXPORT_PASSWORD= \
	-e PORTABLE_BUNDLE_IMPORT_PASSWORD=

echo "[portable-failure] success"
