export const OBJECTS_AUTO_INDEX_DEFAULT_ENABLED = true
export const OBJECTS_AUTO_INDEX_DEFAULT_TTL_HOURS = 12
export const OBJECTS_AUTO_INDEX_TTL_MIN_HOURS = 1
export const OBJECTS_AUTO_INDEX_TTL_MAX_HOURS = 168
